### ISSUE TITLE
RHEL4Edge image build fails in E2E provisioning demo

### ISSUE THREAD

**Issue by giannisalinetti** [redhat-et/microshift-demos#15]
When building the RHEL4Edge image according to the steps suggested by the README the build fails with a RemoteDisconnect from the Red Hat CDN.

The issue has been reproduced with RHEL 8.5 + OCP 4.8. The choice of using RHEL 8.5 went after noticing that the README was not updated with the latest commits on the demo code (see `fddb841409b59cb51cd2c452b9106abd4592d80f`, `d6e1dadcfc8ef5acbf08f7a87b5619d6f32fca98` and `f041ea9b1369717f1bd5f4326b3ec45172b24cdb` commits).

## Steps to reproduce

1. Deploy a RHEL 8.5 instance. During tests a KVM/Libvirt image was deployed on a Fedora 34 host.
2. Register the build vm using `subscription-manager` and attach a pool with valid entitlements. The pool used was the Red Hat's Employee SKU.
3. Enable OCP 4.8 repositories:
    ```
    $ sudo yum-config-manager --enable rhocp-4.8-for-rhel-8-x86_64-rpms
    ```
4. Install `git` and the `oc` client.
5. Clone the microshift-demos repository:
    ```
    $ git clone https://github.com/redhat-et/microshift-demos.git
    $ cd microshift-demos/e2e-demo
    ```
6. Fork the microshift-config repository and store its URL in the GITOPS_REPO variable:
    ```
    $ GITOPS_REPO="https://github.com/giannisalinetti/microshift-config"
    ```
7. Run the build preparation:
    ```
    $ sudo ./image-builder/prepare_builder.sh
    ```
8. Update the kickstart file and run the build script:
    ```
    $ sed -i "s|https://github.com/redhat-et/microshift-config|${GITOPS_REPO}|" ./image-builder/kickstart.ks
    $ sudo ./image-builder/build.sh
    ```

## Build output
```

# Adding RHOCP and Ansible repos to builder

# Loading sources for transmission

# Loading sources for microshift

# Loading r4e-microshift blueprint
blueprint: r4e-microshift v0.0.1
    python3-ethtool-0.14-3.el8.x86_64
    libevent-2.1.8-5.el8.x86_64
    libassuan-2.5.1-3.el8.x86_64
    perl-Scalar-List-Utils-3:1.49-2.el8.x86_64
    perl-PathTools-3.74-1.el8.x86_64
    json-glib-1.4.4-1.el8.x86_64
    perl-Data-Dumper-2.167-399.el8.x86_64
    libedit-3.1-23.20170329cvs.el8.x86_64
    libnfnetlink-1.0.1-13.el8.x86_64
    cracklib-2.9.6-15.el8.x86_64
    libutempter-1.1.6-14.el8.x86_64
    perl-threads-shared-1.58-2.el8.x86_64
    grep-3.1-6.el8.x86_64
    readline-7.0-10.el8.x86_64
    hardlink-1:1.3-6.el8.x86_64
    shared-mime-info-1.9-3.el8.x86_64
    libmnl-1.0.4-6.el8.x86_64
    libyaml-0.1.7-5.el8.x86_64
    perl-Encode-4:2.97-3.el8.x86_64
    gdbm-1:1.18-1.el8.x86_64
    fuse-common-3.2.1-12.el8.x86_64
    pkgconf-1.4.2-1.el8.x86_64
    jansson-2.11-3.el8.x86_64
    libsigsegv-2.11-5.el8.x86_64
    npth-1.5-4.el8.x86_64
    groff-base-1.22.3-18.el8.x86_64
    python3-pyyaml-3.12-12.el8.x86_64
    cracklib-dicts-2.9.6-15.el8.x86_64
    libtasn1-4.13-3.el8.x86_64
    libattr-2.4.48-3.el8.x86_64
    fuse3-libs-3.2.1-12.el8.x86_64
    pkgconf-pkg-config-1.4.2-1.el8.x86_64
    bzip2-libs-1.0.6-26.el8.x86_64
    mpfr-3.1.6-1.el8.x86_64
    acl-2.2.53-1.el8.x86_64
    perl-Unicode-Normalize-1.25-396.el8.x86_64
    libsecret-0.18.6-1.el8.x86_64
    libnetfilter_conntrack-1.0.6-5.el8.x86_64
    libunistring-0.9.9-3.el8.x86_64
    perl-MIME-Base64-3.15-396.el8.x86_64
    libnetfilter_cttimeout-1.0.0-11.el8.x86_64
    less-530-1.el8.x86_64
    python3-inotify-0.9.6-13.el8.noarch
    xz-libs-5.2.4-3.el8.x86_64
    perl-threads-1:2.21-2.el8.x86_64
    perl-Pod-Simple-1:3.35-395.el8.noarch
    perl-Term-ANSIColor-4.06-396.el8.noarch
    dbus-glib-0.110-2.el8.x86_64
    python3-cffi-1.11.5-5.el8.x86_64
    python3-iniparse-0.4-31.el8.noarch
    libnsl2-1.2.0-2.20180605git4a062cf.el8.x86_64
    libverto-0.3.0-5.el8.x86_64
    perl-HTTP-Tiny-0.074-1.el8.noarch
    gobject-introspection-1.56.1-1.el8.x86_64
    libpkgconf-1.4.2-1.el8.x86_64
    publicsuffix-list-dafsa-20180723-1.el8.noarch
    perl-Pod-Escapes-1:1.07-395.el8.noarch
    python3-slip-0.6.4-11.el8.noarch
    python3-decorator-4.2.1-2.el8.noarch
    gdbm-libs-1:1.18-1.el8.x86_64
    python3-pycparser-2.14-14.el8.noarch
    perl-Pod-Perldoc-3.28-396.el8.noarch
    perl-File-Path-2.15-2.el8.noarch
    python3-idna-2.5-5.el8.noarch
    perl-parent-1:0.237-1.el8.noarch
    fuse3-3.2.1-12.el8.x86_64
    pkgconf-m4-1.4.2-1.el8.noarch
    python3-pysocks-1.6.8-3.el8.noarch
    c-ares-1.13.0-5.el8.x86_64
    python3-dateutil-1:2.6.1-6.el8.noarch
    iotop-0.6-16.el8.noarch
    perl-Text-Tabs+Wrap-2013.0523-395.el8.noarch
    xz-5.2.4-3.el8.x86_64
    findutils-1:4.6.0-20.el8.x86_64
    perl-Getopt-Long-1:2.50-4.el8.noarch
    libacl-2.2.53-1.el8.x86_64
    perl-podlators-4.11-1.el8.noarch
    perl-Time-Local-1:1.280-1.el8.noarch
    perl-Carp-1.42-396.el8.noarch
    basesystem-11-5.el8.noarch
    perl-Exporter-5.72-396.el8.noarch
    perl-Storable-1:3.11-3.el8.x86_64
    perl-Text-ParseWords-3.30-395.el8.noarch
    libksba-1.3.5-7.el8.x86_64
    libgpg-error-1.31-1.el8.x86_64
    perl-File-Temp-0.230.600-1.el8.noarch
    perl-constant-1.33-396.el8.noarch
    python3-slip-dbus-0.6.4-11.el8.noarch
    perl-Term-Cap-1.17-395.el8.noarch
    python3-chardet-3.0.4-7.el8.noarch
    perl-Pod-Usage-4:1.69-395.el8.noarch
    python3-six-1.11.0-8.el8.noarch
    ipset-libs-7.1-1.el8.x86_64
    python3-dmidecode-3.12.2-15.el8.x86_64
    gettext-libs-0.19.8.1-17.el8.x86_64
    gettext-0.19.8.1-17.el8.x86_64
    gmp-1:6.1.2-10.el8.x86_64
    checkpolicy-2.9-1.el8.x86_64
    conntrack-tools-1.4.4-10.el8.x86_64
    libnftnl-1.1.5-4.el8.x86_64
    python3-requests-2.20.0-2.1.el8_1.noarch
    libnetfilter_cthelper-1.0.0-15.el8.x86_64
    perl-Socket-4:2.027-3.el8.x86_64
    diffutils-3.6-6.el8.x86_64
    ipset-7.1-1.el8.x86_64
    libidn2-2.2.0-1.el8.x86_64
    libuser-0.62-23.el8.x86_64
    libnl3-3.5.0-1.el8.x86_64
    python3-dbus-1.2.4-15.el8.x86_64
    passwd-0.80-3.el8.x86_64
    info-6.5-6.el8.x86_64
    libnghttp2-1.33.0-3.el8_2.1.x86_64
    pigz-2.4-4.el8.x86_64
    openssl-pkcs11-0.4.10-2.el8.x86_64
    dnf-plugin-subscription-manager-1.26.20-1.el8_2.x86_64
    python3-audit-3.0-0.17.20191104git1c2f876.el8.x86_64
    audit-libs-3.0-0.17.20191104git1c2f876.el8.x86_64
    subscription-manager-rhsm-certificates-1.26.20-1.el8_2.x86_64
    subscription-manager-plugin-ostree-1.26.20-1.el8_2.x86_64
    libzstd-1.4.4-1.el8.x86_64
    kbd-legacy-2.0.4-10.el8.noarch
    net-tools-2.0-0.52.20160912git.el8.x86_64
    gnupg2-smime-2.2.20-2.el8.x86_64
    memstrack-0.1.11-1.el8.x86_64
    libreport-filesystem-2.9.5-15.el8.x86_64
    setup-2.12.2-6.el8.noarch
    gnupg2-2.2.20-2.el8.x86_64
    sed-4.5-2.el8.x86_64
    libcroco-0.6.12-4.el8_2.1.x86_64
    libffi-3.1-22.el8.x86_64
    libnetfilter_queue-1.0.4-3.el8.x86_64
    python3-setuptools-wheel-39.2.0-6.el8.noarch
    kbd-2.0.4-10.el8.x86_64
    libkcapi-hmaccalc-1.2.0-2.el8.x86_64
    python3-setools-4.3.0-2.el8.x86_64
    tar-2:1.30-5.el8.x86_64
    libusbx-1.0.23-4.el8.x86_64
    python3-gobject-base-3.28.3-2.el8.x86_64
    python3-subscription-manager-rhsm-1.26.20-1.el8_2.x86_64
    subscription-manager-1.26.20-1.el8_2.x86_64
    kbd-misc-2.0.4-10.el8.noarch
    pcre2-10.32-2.el8.x86_64
    libkcapi-1.2.0-2.el8.x86_64
    platform-python-setuptools-39.2.0-6.el8.noarch
    p11-kit-trust-0.23.22-1.el8.x86_64
    python3-urllib3-1.24.2-5.el8.noarch
    libpwquality-1.4.4-3.el8.x86_64
    libpsl-0.20.2-6.el8.x86_64
    python3-libselinux-2.9-5.el8.x86_64
    librhsm-0.0.3-4.el8.x86_64
    python3-libsemanage-2.9-6.el8.x86_64
    popt-1.18-1.el8.x86_64
    pciutils-libs-3.7.0-1.el8.x86_64
    libpcap-14:1.9.1-5.el8.x86_64
    cpio-2.12-10.el8.x86_64
    trousers-0.3.15-1.el8.x86_64
    gawk-4.2.1-2.el8.x86_64
    trousers-lib-0.3.15-1.el8.x86_64
    pciutils-3.7.0-1.el8.x86_64
    libselinux-2.9-5.el8.x86_64
    brotli-1.0.6-3.el8.x86_64
    lz4-libs-1.8.3-3.el8_4.x86_64
    libselinux-utils-2.9-5.el8.x86_64
    ima-evm-utils-1.3.2-12.el8.x86_64
    python3-ply-3.9-9.el8.noarch
    procps-ng-3.3.15-6.el8.x86_64
    libseccomp-2.5.1-1.el8.x86_64
    libsemanage-2.9-6.el8.x86_64
    p11-kit-0.23.22-1.el8.x86_64
    iputils-20180629-7.el8.x86_64
    python3-libdnf-0.63.0-3.el8.x86_64
    iptables-ebtables-1.8.4-20.el8.x86_64
    libcap-2.26-5.el8.x86_64
    openssh-8.0p1-10.el8.x86_64
    pam-1.3.1-15.el8.x86_64
    elfutils-libelf-0.185-1.el8.x86_64
    tpm2-tss-2.3.2-4.el8.x86_64
    os-prober-1.74-9.el8.x86_64
    pcre-8.42-6.el8.x86_64
    dnf-data-4.7.0-4.el8.noarch
    perl-libs-4:5.26.3-420.el8.x86_64
    openldap-2.4.46-18.el8.x86_64
    python3-libs-3.6.8-41.el8.x86_64
    which-2.21-16.el8.x86_64
    libuuid-2.32.1-28.el8.x86_64
    libcomps-0.1.16-2.el8.x86_64
    grubby-8.40-42.el8.x86_64
    libmount-2.32.1-28.el8.x86_64
    perl-IO-1.38-420.el8.x86_64
    grub2-tools-minimal-1:2.02-106.el8.x86_64
    perl-interpreter-4:5.26.3-420.el8.x86_64
    dbus-1:1.12.8-14.el8.x86_64
    curl-7.61.1-22.el8.x86_64
    libblkid-2.32.1-28.el8.x86_64
    coreutils-common-8.30-12.el8.x86_64
    iptables-1.8.4-20.el8.x86_64
    virt-what-1.18-12.el8.x86_64
    libssh-0.9.4-3.el8.x86_64
    policycoreutils-2.9-16.el8.x86_64
    nettle-3.4.1-7.el8.x86_64
    dracut-049-191.git20210920.el8.x86_64
    rdma-core-35.0-1.el8.x86_64
    gpgme-1.13.1-9.el8.x86_64
    libcurl-7.61.1-22.el8.x86_64
    crypto-policies-20210617-1.gitc776d3e.el8.noarch
    dbus-libs-1:1.12.8-14.el8.x86_64
    dbus-daemon-1:1.12.8-14.el8.x86_64
    platform-python-3.6.8-41.el8.x86_64
    libcom_err-1.45.6-2.el8.x86_64
    python3-librepo-1.14.0-2.el8.x86_64
    libsolv-0.7.19-1.el8.x86_64
    ncurses-libs-6.1-9.20180224.el8.x86_64
    python3-magic-5.33-20.el8.noarch
    libmodulemd-2.13.0-1.el8.x86_64
    redhat-release-eula-8.5-0.8.el8.x86_64
    ca-certificates-2021.2.50-80.0.el8_4.noarch
    nftables-1:0.9.3-21.el8.x86_64
    libdb-utils-5.3.28-42.el8_4.x86_64
    emacs-filesystem-1:26.1-7.el8.noarch
    filesystem-3.8-6.el8.x86_64
    python3-pip-wheel-9.0.3-20.el8.noarch
    hwdata-0.314-8.10.el8.noarch
    iptables-libs-1.8.4-20.el8.x86_64
    krb5-libs-1.18.2-14.el8.x86_64
    kmod-25-18.el8.x86_64
    usermode-1.113-2.el8.x86_64
    glib2-2.56.4-156.el8.x86_64
    libxcrypt-4.1.1-6.el8.x86_64
    libtirpc-1.1.4-5.el8.x86_64
    policycoreutils-python-utils-2.9-16.el8.noarch
    chkconfig-1.19.1-1.el8.x86_64
    file-libs-5.33-20.el8.x86_64
    libcap-ng-0.7.11-1.el8.x86_64
    crypto-policies-scripts-20210617-1.gitc776d3e.el8.noarch
    libdb-5.3.28-42.el8_4.x86_64
    grub2-common-1:2.02-106.el8.noarch
    json-c-0.13.1-2.el8.x86_64
    bash-4.4.20-2.el8.x86_64
    dbus-tools-1:1.12.8-14.el8.x86_64
    file-5.33-20.el8.x86_64
    python3-dnf-4.7.0-4.el8.noarch
    kmod-libs-25-18.el8.x86_64
    python3-nftables-1:0.9.3-21.el8.x86_64
    ncurses-6.1-9.20180224.el8.x86_64
    coreutils-8.30-12.el8.x86_64
    libssh-config-0.9.4-3.el8.noarch
    python3-cryptography-3.2.1-5.el8.x86_64
    dmidecode-1:3.2-10.el8.x86_64
    libgcrypt-1.8.5-6.el8.x86_64
    elfutils-debuginfod-client-0.185-1.el8.x86_64
    elfutils-libs-0.185-1.el8.x86_64
    librepo-1.14.0-2.el8.x86_64
    openssh-clients-8.0p1-10.el8.x86_64
    platform-python-pip-9.0.3-20.el8.noarch
    python3-libcomps-0.1.16-2.el8.x86_64
    dbus-common-1:1.12.8-14.el8.noarch
    dnf-4.7.0-4.el8.noarch
    shadow-utils-2:4.6-14.el8.x86_64
    libsepol-2.9-3.el8.x86_64
    glibc-common-2.28-164.el8_5.3.x86_64
    openssl-libs-1:1.1.1k-6.el8_5.x86_64
    libgcc-8.5.0-4.el8_5.x86_64
    keyutils-libs-1.5.10-9.el8.x86_64
    rpm-plugin-systemd-inhibit-4.14.3-19.el8_5.2.x86_64
    libfdisk-2.32.1-28.el8.x86_64
    systemd-pam-239-51.el8_5.5.x86_64
    firewalld-0.9.3-7.el8_5.1.noarch
    util-linux-2.32.1-28.el8.x86_64
    python3-hawkey-0.63.0-3.el8.x86_64
    perl-macros-4:5.26.3-420.el8.x86_64
    python3-libxml2-2.9.7-12.el8_5.x86_64
    tzdata-2022a-1.el8.noarch
    systemd-239-51.el8_5.5.x86_64
    ncurses-base-6.1-9.20180224.el8.noarch
    libgomp-8.5.0-4.el8_5.x86_64
    redhat-release-8.5-0.8.el8.x86_64
    libibverbs-35.0-1.el8.x86_64
    gnutls-3.6.16-4.el8.x86_64
    libarchive-3.3.3-3.el8_5.x86_64
    libxml2-2.9.7-12.el8_5.x86_64
    perl-Errno-1.28-420.el8.x86_64
    rpm-build-libs-4.14.3-19.el8_5.2.x86_64
    selinux-policy-3.14.3-80.el8_5.2.noarch
    expat-2.2.5-4.el8_5.3.x86_64
    sqlite-libs-3.26.0-15.el8.x86_64
    cyrus-sasl-lib-2.1.27-6.el8_5.x86_64
    python3-rpm-4.14.3-19.el8_5.2.x86_64
    selinux-policy-targeted-3.14.3-80.el8_5.2.noarch
    python3-policycoreutils-2.9-16.el8.noarch
    python3-dnf-plugins-core-4.0.21-4.el8_5.noarch
    rpm-libs-4.14.3-19.el8_5.2.x86_64
    systemd-libs-239-51.el8_5.5.x86_64
    cryptsetup-libs-2.3.3-4.el8_5.1.x86_64
    python3-firewall-0.9.3-7.el8_5.1.noarch
    rpm-plugin-selinux-4.14.3-19.el8_5.2.x86_64
    elfutils-default-yama-scope-0.185-1.el8.noarch
    python3-gpg-1.13.1-9.el8.x86_64
    linux-firmware-20210702-104.gitd79c2677.el8_5.noarch
    openssl-1:1.1.1k-6.el8_5.x86_64
    lua-libs-5.3.4-12.el8.x86_64
    libdnf-0.63.0-3.el8.x86_64
    libsmartcols-2.32.1-28.el8.x86_64
    glibc-2.28-164.el8_5.3.x86_64
    device-mapper-libs-8:1.02.177-11.el8_5.x86_64
    glibc-all-langpacks-2.28-164.el8_5.3.x86_64
    python3-syspurpose-1.28.21-5.el8_5.x86_64
    systemd-udev-239-51.el8_5.5.x86_64
    libstdc++-8.5.0-4.el8_5.x86_64
    rpm-4.14.3-19.el8_5.2.x86_64
    device-mapper-8:1.02.177-11.el8_5.x86_64
    firewalld-filesystem-0.9.3-7.el8_5.1.noarch
    grub2-tools-1:2.02-106.el8.x86_64
    gzip-1.9-13.el8_5.x86_64
    kpartx-0.8.4-17.el8_5.1.x86_64
    kernel-modules-4.18.0-348.23.1.el8_5.x86_64
    kernel-4.18.0-348.23.1.el8_5.x86_64
    kernel-core-4.18.0-348.23.1.el8_5.x86_64
    zlib-1.2.11-18.el8_5.x86_64
    geolite2-city-20180605-1.el8.noarch
    python3-jmespath-0.9.0-11.el8.noarch
    geolite2-country-20180605-1.el8.noarch
    perl-IO-Socket-IP-0.39-5.el8.noarch
    perl-libnet-3.11-3.el8.noarch
    python3-pytz-2017.2-9.el8.noarch
    perl-Error-1:0.17025-2.el8.noarch
    perl-Digest-1.17-395.el8.noarch
    perl-TermReadKey-2.37-7.el8.x86_64
    perl-URI-1.73-3.el8.noarch
    libnet-1.1.6-15.el8.x86_64
    perl-Digest-MD5-2.55-396.el8.x86_64
    pinentry-1.1.0-2.el8.x86_64
    python3-markupsafe-0.23-19.el8.x86_64
    libxkbcommon-0.9.1-1.el8.x86_64
    xkeyboard-config-2.28-1.el8.noarch
    perl-IO-Socket-SSL-2.066-4.module+el8.3.0+6446+594cad75.noarch
    perl-Mozilla-CA-20160104-7.module+el8.3.0+6498+9eecfe51.noarch
    perl-Net-SSLeay-1.88-1.module+el8.3.0+6446+594cad75.x86_64
    git-core-2.27.0-1.el8.x86_64
    libmaxminddb-1.2.0-10.el8.x86_64
    perl-Git-2.27.0-1.el8.noarch
    git-2.27.0-1.el8.x86_64
    git-core-doc-2.27.0-1.el8.noarch
    protobuf-c-1.3.0-6.el8.x86_64
    rhc-worker-playbook-0.1.5-3.el8_4.x86_64
    criu-3.15-3.module+el8.5.0+12582+56d94c81.x86_64
    libslirp-4.4.0-1.module+el8.5.0+12582+56d94c81.x86_64
    slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    unbound-libs-1.7.3-17.el8.x86_64
    bind-libs-32:9.11.26-6.el8.x86_64
    fstrm-0.6.1-2.el8.x86_64
    bind-license-32:9.11.26-6.el8.noarch
    bind-libs-lite-32:9.11.26-6.el8.x86_64
    python3-babel-2.5.1-7.el8.noarch
    python3-jinja2-2.10.1-3.el8.noarch
    python3-bind-32:9.11.26-6.el8.noarch
    python3-unbound-1.7.3-17.el8.x86_64
    bind-utils-32:9.11.26-6.el8.x86_64
    rhc-1:0.2.0-3.el8.x86_64
    insights-client-3.1.7-1.el8_5.noarch
    containernetworking-plugins-1.0.1-1.module+el8.5.0+13436+9c05b4ba.x86_64
    runc-1.0.3-1.module+el8.5.0+13556+7f055e70.x86_64
    containers-common-2:1-8.module+el8.5.0+13954+1b78b731.noarch
    container-selinux-2:2.173.0-1.module+el8.5.0+13852+150547f7.noarch
    conmon-2:2.0.32-1.module+el8.5.0+13852+150547f7.x86_64
    podman-1:3.4.2-9.module+el8.5.0+13852+150547f7.x86_64
    fuse-overlayfs-1.8-1.module+el8.5.0+13754+92ec836b.x86_64
    podman-catatonit-1:3.4.2-9.module+el8.5.0+13852+150547f7.x86_64
    cri-tools-1.21.0-4.el8.x86_64
    cri-o-1.21.6-3.rhaos4.8.git19780ee.2.el8.x86_64
    sshpass-1.06-3.el8ae.x86_64
    ansible-2.9.27-1.el8ae.noarch
    microshift-4.8.0-2022_04_20_141053.el8.x86_64
    microshift-selinux-4.8.0-2022_04_20_141053.el8.noarch
    transmission-agent-0.1.6-1.el8.noarch

# Building r4e-microshift ostree container image
2022-05-10 01:02:37 FAILED
Blueprint build has failed. For more info, download logs from composer.
```

From the compose logs the `RemoteDisconnect` status is displayed.
```
$ sudo composer-cli compose logs 115e1a35-858e-4dae-b88b-cd4085b59d00 --json
2022-05-10 01:05:02,106: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

A `tcpdump` shows an initial handshake between the builder VM and the Akamai CDN and a consistent amount of traffic.

Manual package installations from the host work correctly, proving that the CDN can be reached from the VM.

## Expected results
Builds completes successfully and the resulting ISO image is dropped in the `builds` folder.

## Alternate tests with RHEL 8.4
The same issue and results were also reproduced with RHEL 8.4 + OCP 4.7 after some minor adjustments (add `/etc/osbuild-composer/repositories/rhel84.json` file as a copy of the repo `rhel8.json` and fix type of composer CLI command parameter with `rhel-edge-container` and `rhel-edge-installer`.

**Comment by giannisalinetti** [comment]
Update: I have found the root cause in the traceback of the `osbuild-worker` process in `/var/log/messages` file. This points out to a broken url for the Microshift copr repository.

```
May 10 07:22:10 r4e-builder osbuild-worker[6397]: time="2022-05-10T07:22:10-04:00" level=info msg="Running job '36f24c36-bb31-4a14-bdb3-9db9d9985a36' (osbuild)\n"
May 10 07:22:12 r4e-builder osbuild-worker[6397]: Traceback (most recent call last):
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/bin/osbuild", line 11, in <module>
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    load_entry_point('osbuild==53', 'console_scripts', 'osbuild')()
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib/python3.6/site-packages/osbuild/main_cli.py", line 158, in osbuild_cli
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    manifest.download(object_store, monitor, args.libdir)
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib/python3.6/site-packages/osbuild/pipeline.py", line 371, in download
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    source.download(mgr, store, libdir)
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib/python3.6/site-packages/osbuild/sources.py", line 38, in download
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    reply = client.call_with_fds("download", args, fds)
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib/python3.6/site-packages/osbuild/host.py", line 375, in call_with_fds
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    raise error
May 10 07:22:12 r4e-builder osbuild-worker[6397]: osbuild.host.RemoteError: RuntimeError: curl: error downloading {'url': 'https://download.copr.fedorainfracloud.org/results/@redhat-et/microshift/epel-8-$basearch/04294330-microshift/microshift-4.8.0-2022_04_20_141053.el8.x86_64.rpm'}: error code 22
May 10 07:22:12 r4e-builder osbuild-worker[6397]:   File "/usr/lib/python3.6/site-packages/osbuild/host.py", line 268, in serve
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    reply, reply_fds = self._handle_message(msg, fds)
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib/python3.6/site-packages/osbuild/host.py", line 301, in _handle_message
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    ret, fds = self.dispatch(name, args, fds)
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib/python3.6/site-packages/osbuild/sources.py", line 64, in dispatch
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    args["options"])
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib/osbuild/sources/org.osbuild.curl", line 172, in download
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    download(items, cache)
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib/osbuild/sources/org.osbuild.curl", line 162, in download
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    for _ in results:
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    for element in iterable:
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    yield fs.pop().result()
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    return self.__get_result()
May 10 07:22:12 r4e-builder osbuild-worker[6397]:  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
May 10 07:22:12 r4e-builder osbuild-worker[6397]:    raise self._exception
May 10 07:22:12 r4e-builder osbuild-worker[6397]: time="2022-05-10T07:22:12-04:00" level=error msg="osbuild job failed: osbuild build failed" jobId=36f24c36-bb31-4a14-bdb3-9db9d9985a36
May 10 07:22:12 r4e-builder osbuild-worker[6397]: time="2022-05-10T07:22:12-04:00" level=warning msg="Job '36f24c36-bb31-4a14-bdb3-9db9d9985a36' (osbuild) failed: error decoding osbuild output: unexpected end of JSON input\nthe raw output:\n"
```
Replacing `$basearch` with the `$(uname -i)` value fixes the issue.
